// Lastep : traduction anglaise (clé = texte français exact)
window.EN_DICT={
"Damier": "Checkers",
"Forteresse": "Fortress",
"Rivière": "River",
"Croix": "Cross",
"Diagonales": "Diagonals",
"Couronne": "Crown",
"Sablier": "Hourglass",
"Îlots": "Islands",
"Moulin": "Mill",
"Colonnes": "Columns",
"Débutant": "Beginner",
"Facile": "Easy",
"Facile +": "Easy +",
"Moyen": "Medium",
"Moyen +": "Medium +",
"Difficile": "Hard",
"Expert": "Expert",
"Gratuit": "Free",
"Ivoire": "Ivory",
"Azur": "Azure",
"Corail": "Coral",
"Menthe": "Mint",
"Lavande": "Lavender",
"Rose": "Pink",
"Nuit": "Night",
"Or": "Gold",
"Lisse": "Smooth",
"Poilu": "Furry",
"Piquant": "Spiky",
"Cube": "Cube",
"Ronds": "Round",
"Rieurs": "Smiling",
"Furieux": "Furious",
"Étoiles": "Stars",
"Aucun": "None",
"Casquette": "Cap",
"Lunettes": "Glasses",
"Cornes": "Horns",
"Nœud": "Bow",
"Auréole": "Halo",
"Néon": "Neon",
"Lave": "Lava",
"Toxique": "Toxic",
"Glace": "Ice",
"Couleur": "Color",
"Fourrure": "Fur",
"Yeux": "Eyes",
"Accessoire": "Accessory",
"Plateau": "Board",
"Oh, c'est moi qui mène ?": "Oh, am I winning?",
"Je joue au hasard et je te tiens.": "I'm playing randomly and I've still got you.",
"Tu veux un indice ?": "Need a hint?",
"Hihi, gagné !": "Hehe, I won!",
"Même moi je te bats.": "Even I can beat you.",
"Bien joué… je retourne réviser.": "Well played… back to studying.",
"Aïe, mes oreilles !": "Ouch, my ears!",
"Hé, doucement !": "Hey, easy!",
"Hihi.": "Hehe.",
"Concentre-toi plutôt.": "Focus instead.",
"Tu tapes plus vite que tu joues.": "You type faster than you play.",
"Je suis peut-être une princesse, mais je joue.": "I may be a princess, but I can play.",
"Attention à tes cases !": "Watch your tiles!",
"Oups, c'était ma case préférée.": "Oops, that was my favorite tile.",
"Merci pour la partie !": "Thanks for the game!",
"Hihi, j'ai gagné.": "Hehe, I won.",
"Bien joué ! Tu m'apprends ?": "Well played! Will you teach me?",
"Hé, pas de wizz !": "Hey, no buzzing!",
"Doucement…": "Easy…",
"Courage !": "Hang in there!",
"On joue ?": "Shall we play?",
"Joli coup.": "Nice move.",
"Je te colle.": "I'm on your tail.",
"Tu ne m'échapperas pas.": "You won't escape me.",
"Ça chauffe, hein ?": "Getting hot, huh?",
"Brûlé.": "Burned.",
"Trop facile.": "Too easy.",
"Grr… revanche.": "Grr… rematch.",
"Ça m'énerve encore plus.": "That makes me even angrier.",
"Tu joues avec le feu.": "You're playing with fire.",
"Grr.": "Grr.",
"Avance.": "Move.",
"Tu trembles ?": "Shaking?",
"Le Prof": "The Prof",
"Un pas après l'autre.": "One step at a time.",
"Compte tes cases.": "Count your tiles.",
"Garde ton saut pour la fin.": "Save your jump for the end.",
"Leçon du jour : la patience.": "Today's lesson: patience.",
"On revoit ça ensemble ?": "Shall we review it together?",
"Excellent. Tu progresses.": "Excellent. You're improving.",
"Un wizz n'est pas un coup.": "A buzz is not a move.",
"Réfléchis.": "Think.",
"Bonne idée.": "Good idea.",
"Regarde ses sorties.": "Look at their exits.",
"Tes cases fondent.": "Your tiles are melting.",
"Je vois tes deux pions… et leur fin.": "I see your two pawns… and their end.",
"Trop lent.": "Too slow.",
"Rien ne passe.": "Nothing gets through.",
"Mur porteur : moi.": "Load-bearing wall: me.",
"Tu as trouvé la faille. Pas deux fois.": "You found the gap. Not twice.",
"Toc toc ? Personne.": "Knock knock? Nobody home.",
"Ça ne me fait rien.": "Doesn't bother me.",
"Parle moins, joue mieux.": "Talk less, play better.",
"Hm.": "Hm.",
"On verra au prochain coup.": "We'll see next move.",
"Je calcule ta défaite.": "Calculating your defeat.",
"Encore trois coups et tu es coincé.": "Three more moves and you're stuck.",
"Tu sens le plateau se refermer ?": "Feel the board closing in?",
"Aspiré.": "Sucked in.",
"Prévisible.": "Predictable.",
"Bug. Revanche.": "Bug. Rematch.",
"Tu crois que ça me déconcentre ?": "Think that distracts me?",
"Mes calculs continuent.": "My calculations continue.",
"Négatif.": "Negative.",
"Calcul en cours…": "Calculating…",
"Tu as déjà perdu, tu ne le sais pas encore.": "You've already lost, you just don't know it yet.",
"Le Sphinx": "The Sphinx",
"Je vois la fin. Elle ne te plaît pas.": "I see the end. You won't like it.",
"Intéressant. Faux, mais intéressant.": "Interesting. Wrong, but interesting.",
"Respire, ça va bien se passer. Pour moi.": "Breathe, it'll go fine. For me.",
"Comme prévu.": "As planned.",
"Reviens quand tu seras prêt.": "Come back when you're ready.",
"Remarquable. Je me souviendrai de toi.": "Remarkable. I will remember you.",
"Un wizz ? Quelle audace.": "A buzz? How bold.",
"Ton agitation me nourrit.": "Your panic feeds me.",
"Silence.": "Silence.",
"Joue.": "Play.",
"Les mots ne déplacent aucun pion.": "Words don't move pawns.",
"Politesse": "Manners",
"Salut !": "Hi!",
"Bonne partie !": "Have a good game!",
"GG": "GG",
"Bien joué.": "Well played.",
"Merci !": "Thanks!",
"Au revoir.": "Bye.",
"Encouragements": "Encouragement",
"Joli coup !": "Nice move!",
"Bravo !": "Bravo!",
"Pas mal du tout.": "Not bad at all.",
"Oups.": "Oops.",
"Revanche ?": "Rematch?",
"On se calme.": "Calm down.",
"Piques": "Taunts",
"Tu es bloqué ?": "Stuck?",
"Le dernier pas, c'est pour moi.": "The last step is mine.",
"Tu cherches la sortie ?": "Looking for the exit?",
"Garde ton saut, tu vas en avoir besoin.": "Keep your jump, you'll need it.",
"Même Pépin joue mieux.": "Even Pépin plays better.",
"Je vois ta défaite d'ici.": "I can see your defeat from here.",
"C'était ton plan, ça ?": "Was that your plan?",
"Il te reste combien de cases ?": "How many tiles do you have left?",
"Prends ton temps… ou pas.": "Take your time… or don't.",
"Un seul saut. Tu l'as gaspillé.": "One jump. You wasted it.",
"Je t'attends au prochain coup.": "See you next move.",
"Le sol tremble sous tes pieds.": "The ground is shaking under you.",
"Ça sent la fin.": "Smells like the end.",
"Zéro case, zéro chance.": "Zero tiles, zero chance.",
"Bloqué. Comme prévu.": "Blocked. As planned.",
"Toi": "You",
"Argent": "Silver",
"Platine": "Platinum",
"Diamant": "Diamond",
"Adversaire": "Opponent",
"Joueur 1": "Player 1",
"Joueur 2": "Player 2",
"Invité": "Guest",
"Les deux pions de": "Both pawns of",
"sont bloqués.": "are blocked.",
"Un pion de": "A pawn of",
"est bloqué : il joue l'autre.": "is blocked: the other one plays.",
"utilise son saut ↷": "uses their jump ↷",
"plus grande somme restante (": "highest remaining sum (",
"sommes égales, victoire la plus rapide (": "equal sums, fastest win (",
"coups)": "moves)",
"égalité parfaite, le vainqueur de la manche 1 commence": "perfect tie, the round 1 winner starts",
"Ton prémove n'était plus possible.": "Your premove was no longer possible.",
"Coup annulé.": "Move undone.",
"Victoire manquée": "Missed win",
"Coup perdant": "Losing move",
"Imprécision": "Inaccuracy",
"Coup gagnant": "Winning move",
"Bon coup": "Good move",
"Wizz envoyé !": "Buzz sent!",
"Toc toc toc envoyé !": "Knock knock sent!",
"Hahaha envoyé !": "Hahaha sent!",
"un wizz": "a buzz",
"un toc toc toc": "a knock knock",
"un gros HAHAHA": "a big HAHAHA",
"Tu as bloqué les taquineries : tu ne peux pas en envoyer.": "You blocked teasing: you can't send any.",
"Ton adversaire a bloqué les taquineries.": "Your opponent blocked teasing.",
"Ton adversaire": "Your opponent",
"t'envoie": "sends you",
"Ton adversaire n'a pas joué son premier coup à temps.": "Your opponent didn't play their first move in time.",
"Partie annulée par une coupure de connexion.": "Game cancelled: connection lost.",
"Adversaire trouvé :": "Opponent found:",
"Cette partie a déjà deux joueurs.": "This game already has two players.",
"abandonne la partie.": "resigns the game.",
"Ton adversaire s'est déconnecté.": "Your opponent disconnected.",
"Connexion impossible pour le moment.": "Can't connect right now.",
"Aucune partie avec ce code. Vérifie le code, et que ton ami a toujours l'écran ouvert.": "No game with this code. Check the code, and that your friend still has the screen open.",
"Connexion au service en ligne impossible. Vérifie ta connexion internet.": "Can't reach the online service. Check your internet connection.",
"La connexion a échoué. Réessaie.": "Connection failed. Try again.",
"Viens me défier sur Lastep. Code :": "Come challenge me on Lastep. Code:",
"Lien copié": "Link copied",
"Copie impossible": "Couldn't copy",
"La belle": "Decider",
"Manche": "Round",
"· plateau": "· board",
"Saut disponible": "Jump available",
"Saut déjà utilisé": "Jump already used",
"manches · plateau": "rounds · board",
"· entraînement": "· training",
"en ligne": "online",
", pion de": ", pawn of",
"Pose ta bombe": "Place your bomb",
": touche une case. Si l'adversaire marche dessus pendant ses 3 premiers coups, il perd la manche.": ": tap a tile. If your opponent steps on it during their first 3 moves, they lose the round.",
"remporte la partie": "wins the game",
"gagne la manche.": "wins the round.",
"réfléchit…": "is thinking…",
"Prémove prêt :": "Premove ready:",
"Prémove : touche la case visée.": "Premove: tap the target tile.",
"Tour adverse. Tu peux préparer ton coup.": "Opponent's turn. You can prepare your move.",
"Au tour de": "Turn:",
"Recherche du meilleur coup…": "Looking for the best move…",
": choisis un pion": ": pick a pawn",
"À toi : choisis un pion": "Your turn: pick a pawn",
"Touche une case marquée. ↷ = ton saut, utilisé automatiquement": "Tap a marked tile. ↷ = your jump, used automatically",
"Touche une case marquée": "Tap a marked tile",
"Indice": "Hint",
"Annuler": "Undo",
"Chat": "Chat",
"Bloqué": "Blocked",
"Wizz": "Buzz",
"Toc toc": "Knock",
"Haha": "Haha",
"Quitter": "Leave",
"Abandon": "Resign",
"Analyser": "Analyze",
"Résultats": "Results",
"Menu": "Menu",
"Rejouer": "Play again",
"Évolution de tes steps": "Your steps over time",
"⏱️ Défis chrono": "⏱️ Timed challenges",
"Jouer": "Play",
"Partager": "Share",
"3 puzzles · 1 essai": "3 puzzles · 1 try",
"Éclair": "Blitz",
"En ligne": "Online",
"Défier": "Challenge",
"steps ·": "steps ·",
"Série de": "Streak:",
"🧩 Puzzles": "🧩 Puzzles",
"Résoudre": "Solve",
"Lastep du jour #": "Daily Lastep #",
"Stats": "Stats",
"Amis": "Friends",
"Ajouter": "Add",
"+100 pièces par ami qui rejoint": "+100 coins per friend who joins",
"À deux sur ce téléphone": "Two players, one phone",
"Retour": "Back",
"Commencer la partie": "Start the game",
"Jouer avec un ami": "Play with a friend",
"Jouer contre l'ordinateur": "Play the computer",
"Jouer avec l'entraîneur": "Play with the coach",
"Plus": "More",
"Équipé": "Equipped",
"Possédé": "Owned",
"Plateaux": "Boards",
"Premium est actif sur cet appareil.": "Premium is active on this device.",
"Bientôt disponible en abonnement.": "Subscription coming soon.",
"Soutenir le jeu": "Support the game",
"Boutique": "Shop",
"pièces": "coins",
"Plus tu joues, plus tu en gagnes : 2 par minute de jeu, 10 par victoire, 3 par partie terminée, et des bonus pour les cours, puzzles et badges.": "The more you play, the more you earn: 2 per minute played, 10 per win, 3 per finished game, plus bonuses for lessons, puzzles and badges.",
"Toute la personnalisation s'achète avec tes pièces. Touche un objet pour l'acheter ou l'équiper.": "All customization is bought with your coins. Tap an item to buy or equip it.",
"Premium": "Premium",
"Pour devenir meilleur, pas pour la déco :": "To get better, not for looks:",
"Cours avancés": "Advanced lessons",
"Indices et solutions des puzzles et des cours": "Hints and solutions for puzzles and lessons",
"Analyses de parties illimitées": "Unlimited game analysis",
"Bloquer wizz, toc toc et haha": "Block buzz, knock and haha",
"· Premium actif": "· Premium active",
"Personnalisation": "Customization",
"Classements par cadence · 5×5": "Rankings by time control · 5×5",
"Chaque cadence a son propre classement. Classement national : bientôt, avec le serveur de comptes.": "Each time control has its own ranking. National ranking: coming soon, with player accounts.",
"Parties contre de vrais joueurs ·": "Games against real players ·",
"Tout voir ›": "See all ›",
"Tes parties en ligne et contre tes amis apparaîtront ici.": "Your online games and games with friends will show up here.",
"Statistiques": "Statistics",
"analyses · +1 dans": "analyses · +1 in",
"analyses cette semaine": "analyses this week",
"matchs classés": "ranked games",
"puzzles réussis": "puzzles solved",
"cases détruites": "tiles destroyed",
"parties jouées": "games played",
"Badges ·": "Badges ·",
"Amis ·": "Friends ·",
"Répertoire": "Contacts",
"Mon poster": "My poster",
"Réglages": "Settings",
"À propos": "About",
"Lastep ·": "Lastep ·",
"Confidentialité": "Privacy",
"Site": "Website",
"· contact :": "· contact:",
"Profil": "Profile",
"Pseudo": "Nickname",
"Code ami :": "Friend code:",
"Accueil": "Home",
"Puzzles": "Puzzles",
"Apprendre": "Learn",
"Fermer": "Close",
"Cadence": "Time control",
"Temps par joueur et par manche. Éclair : une seule manche d'une minute.": "Time per player per round. Blitz: a single one-minute round.",
"Choisis ton adversaire": "Choose your opponent",
"Partie piégée 💣": "Trapped game 💣",
"Une bombe cachée chacun, active 3 coups.": "One hidden bomb each, active for 3 moves.",
"Jouer ·": "Play ·",
"Le module en ligne n'a pas pu se charger. Vérifie ta connexion internet et relance l'appli.": "The online module couldn't load. Check your internet connection and restart the app.",
"Crée une partie et envoie le lien à ton ami, ou entre le code qu'il t'a envoyé. Cadence :": "Create a game and send the link to your friend, or enter the code they sent you. Time control:",
"Créer une partie": "Create a game",
"CODE": "CODE",
"Code de la partie": "Game code",
"Rejoindre": "Join",
"Le code fait 5 caractères.": "The code has 5 characters.",
"Partie en ligne": "Online game",
"ton ami": "your friend",
"Défi envoyé à": "Challenge sent to",
"Envoie le lien à ton ami et garde cet écran ouvert. La partie démarre dès qu'il arrive.": "Send the link to your friend and keep this screen open. The game starts as soon as they arrive.",
"Connexion au service en ligne…": "Connecting to the online service…",
"Partie créée ·": "Game created ·",
"Envoyer l'invitation": "Send the invite",
"Connexion à la partie": "Joining the game",
"Ton ami doit garder l'écran de la partie ouvert.": "Your friend must keep the game screen open.",
"Plus d'analyse gratuite": "No free analysis left",
"Tu as utilisé tes 3 analyses des 7 derniers jours. La prochaine se libère dans": "You've used your 3 analyses for the last 7 days. The next one unlocks in",
"h. Les analyses illimitées arriveront avec Premium.": "h. Unlimited analysis will come with Premium.",
"Puzzles Premium": "Premium puzzles",
"Les": "The first",
"premiers puzzles sont gratuits. La suite du parcours fait partie de Premium.": "puzzles are free. The rest of the path is part of Premium.",
"D'accord": "OK",
"Plus d'essai aujourd'hui": "No tries left today",
"Sans Premium, tu as": "Without Premium, you get",
"défis chrono par jour. Reviens demain, ou passe Premium pour jouer sans limite.": "timed challenges per day. Come back tomorrow, or go Premium to play without limits.",
"Cours Premium": "Premium lesson",
"Ce cours fait partie de Premium : il apprend les techniques des meilleurs joueurs. Premium arrive bientôt en abonnement.": "This lesson is part of Premium: it teaches the techniques of the best players. Premium subscription coming soon.",
"Indices · Premium": "Hints · Premium",
"Les indices et les solutions des cours et des puzzles font partie de Premium. Sans indice, cherche par toi-même : c'est comme ça qu'on progresse le plus.": "Hints and solutions for lessons and puzzles are part of Premium. Without hints, search on your own: that's how you improve the most.",
"Je cherche encore": "I'll keep looking",
"Tournois · bientôt": "Tournaments · soon",
"Les tournois, ligues et classements mondiaux arriveront avec les comptes joueurs et le serveur de l'application.": "Tournaments, leagues and world rankings will come with player accounts and the game server.",
"Tournois · Premium": "Tournaments · Premium",
"Tournois éclair, ligues et trophées sont réservés aux membres Premium.": "Blitz tournaments, leagues and trophies are for Premium members.",
"Voir Premium": "See Premium",
"Acheter et équiper ·": "Buy and equip ·",
"Il te manque": "You need",
"pièces. Joue des parties, des puzzles et des cours pour en gagner.": "more coins. Play games, puzzles and lessons to earn some.",
"Prix :": "Price:",
"Quitter la partie ?": "Leave the game?",
"Abandonner la partie ?": "Resign the game?",
"La partie comptera comme une défaite pour ton classement.": "The game will count as a loss for your ranking.",
"Ton adversaire gagne la partie et tu perds des points de championnat.": "Your opponent wins the game and you lose ranking points.",
"Tu retournes au menu.": "You'll go back to the menu.",
"Abandonner": "Resign",
"Continuer": "Continue",
"Entre le code pour débloquer Premium sur cet appareil.": "Enter the code to unlock Premium on this device.",
"Désactiver Premium": "Turn off Premium",
"Accès administrateur": "Admin access",
"Code administrateur": "Admin code",
"Valider": "Confirm",
"Code incorrect.": "Wrong code.",
"+500 pièces (test)": "+500 coins (test)",
"Ajouter un ami": "Add a friend",
"Ton code ami": "Your friend code",
"CODE AMI": "FRIEND CODE",
"Code ami de ton ami": "Your friend's code",
"Un code ami fait 8 caractères, par exemple ABCD-EFGH.": "A friend code has 8 characters, for example ABCD-EFGH.",
"Partager mon lien": "Share my link",
"La recherche par pseudo arrivera avec les comptes joueurs (serveur). En attendant : code ami, lien ou répertoire.": "Search by nickname will come with player accounts. For now: friend code, link or contacts.",
"Ami introuvable": "Friend not found",
"En ligne maintenant": "Online now",
"Championnat": "Championship",
"Défier ·": "Challenge ·",
"Ton ami doit avoir le jeu ouvert pour recevoir un défi. Sinon, crée une partie et envoie-lui le lien.": "Your friend needs the game open to receive a challenge. Otherwise, create a game and send them the link.",
"Créer une partie et envoyer le lien": "Create a game and send the link",
"Code": "Code",
"Puzzles réussis :": "Puzzles solved:",
"· Badges :": "· Badges:",
"Retirer de mes amis": "Remove from friends",
"te défie !": "challenges you!",
"Partie en ligne ·": "Online game ·",
"min par joueur · plateau 5×5.": "min per player · 5×5 board.",
"Accepter": "Accept",
"Refuser": "Decline",
"Jeu en ligne": "Online play",
"Réessayer": "Try again",
"Changer de cadence": "Change time control",
"Personne d'autre ne cherche à cette cadence pour l'instant.": "Nobody else is searching at this time control right now.",
"Jouer contre": "Play",
"(l'ordinateur) en attendant": "(computer) while you wait",
"Recherche d'un adversaire…": "Looking for an opponent…",
"La partie démarre dès qu'un autre joueur cherche en même temps que toi. Garde cet écran ouvert.": "The game starts as soon as another player searches at the same time. Keep this screen open.",
"Annuler la recherche": "Cancel search",
"Seuls les joueurs qui cherchent en même temps que toi se trouvent. Partage le jeu pour qu'il y ait du monde !": "Only players searching at the same time as you can meet. Share the game to bring more players!",
"réussi": "solved",
"pour valider": "to clear",
"Lastep du jour": "Daily Lastep",
"· série de": "· streak:",
"Lastep #": "Lastep #",
"/3 en": "/3 in",
"Partager mon résultat": "Share my result",
"Le résultat se partage sans dévoiler la solution. Nouveau puzzle demain.": "Your result is shared without revealing the solution. New puzzle tomorrow.",
"Réussi en": "Solved in",
"Raté…": "Missed…",
"Tu bats": "You beat",
"a fait": "did",
"s. Encore un effort !": "s. One more try!",
"l'a réussi en": "solved it in",
"Renvoyer le défi": "Send the challenge back",
"La vidéo n'a pas pu être créée sur ce téléphone.": "The video couldn't be created on this phone.",
"Création de la vidéo… (5 secondes)": "Creating the video… (5 seconds)",
"Ton coup gagnant en vidéo": "Your winning move as a video",
"Format vertical pour TikTok, Reels et Shorts : « Trouveras-tu le coup gagnant ? »": "Vertical format for TikTok, Reels and Shorts: “Can you find the winning move?”",
"Bien joué !": "Well played!",
"L'essentiel tient en trois phrases :": "The essentials in three sentences:",
"Bloque les": "Block both",
"pions adverses pour gagner la manche.": "of your opponent's pawns to win the round.",
"Les cases s'usent et tombent quand on les quitte.": "Tiles wear out and fall when you leave them.",
"Une fois par manche, ton pion peut": "Once per round, your pawn can",
"Jouer ma première partie": "Play my first game",
"Voir le cours suivant": "See the next lesson",
"Sans limite.": "Unlimited.",
"aujourd'hui.": "today.",
"Défis chrono": "Timed challenges",
"Une erreur ou le temps écoulé : fin. Série : 3 erreurs permises.": "One mistake or time out: it's over. Streak: 3 mistakes allowed.",
"Leçon terminée !": "Lesson complete!",
"Bien joué,": "Well played,",
"Terminer": "Finish",
"COURS PREMIUM": "PREMIUM LESSON",
"LIMITE QUOTIDIENNE ATTEINTE": "DAILY LIMIT REACHED",
"Des puzzles illimités": "Unlimited puzzles",
"Des cours illimités": "Unlimited lessons",
"Ce cours fait partie de Premium.": "This lesson is part of Premium.",
"Tes": "Your",
"puzzles du jour sont faits. Reviens demain, ou passe Premium.": "puzzles for today are done. Come back tomorrow, or go Premium.",
"Ton cours gratuit du jour est fait. Reviens demain, ou passe Premium.": "Your free lesson for today is done. Come back tomorrow, or go Premium.",
"Passer Premium": "Go Premium",
"Badges": "Badges",
"Il a résolu ce puzzle en": "They solved this puzzle in",
"s. Fais mieux ?": "s. Can you beat that?",
"Relever le défi": "Take the challenge",
"Toutes": "All",
"Aucune partie pour l'instant.": "No games yet.",
"Parties contre de vrais joueurs": "Games against real players",
"Filtrer": "Filter",
"Poster de": "Poster of",
"Le poster n'a pas pu être créé.": "The poster couldn't be created.",
"Création du poster…": "Creating the poster…",
"Ton poster": "Your poster",
"Enregistrer": "Save",
"Format 1080×1350 pour Instagram, TikTok ou WhatsApp. Le classement national s'affichera quand le serveur de comptes sera en place.": "1080×1350 format for Instagram, TikTok or WhatsApp. The national ranking will show once player accounts are live.",
"Retour au menu": "Back to menu",
"Quitter la partie": "Leave the game",
"Confirmer l'abandon": "Confirm resignation",
"(compte comme une défaite)": "(counts as a loss)",
"Partie": "Game",
"Règles du jeu": "Game rules",
"Sons": "Sounds",
"Musique": "Music",
"Mes piques": "My taunts",
"Messages": "Messages",
"Choisir mes": "Choose my",
"Choisis les": "Choose the",
"phrases que tu pourras envoyer pendant tes parties.": "phrases you'll be able to send during your games.",
", perdant +": ", loser +",
"pts (10 +": "pts (10 +",
"cases)": "tiles)",
"gagne la manche": "wins the round",
"Une manche partout : on joue la belle.": "One round each: time for the decider.",
"commence la manche": "starts the round",
"steps (": "steps (",
"Comment jouer": "How to play",
"Deux pions chacun.": "Two pawns each.",
"Chaque manche se joue sur un plateau tiré au sort parmi 10, symétrique : même position pour les deux.": "Each round is played on a board drawn from 10, symmetrical: same position for both players.",
"À ton tour": "On your turn",
", bouge un pion de 1, 2 ou 3 cases en ligne droite.": ", move a pawn 1, 2 or 3 tiles in a straight line.",
"Obstacles.": "Obstacles.",
"Jamais sur un pion ni par-dessus. Un trou bloque la ligne.": "Never onto or over a pawn. A hole blocks the line.",
"Saut ↷.": "Jump ↷.",
"Une fois par manche, ton pion peut passer par-dessus trous et pions. Les cases marquées ↷ l'utilisent automatiquement. Le badge « Saut dispo » sous ton nom te dit s'il te reste.": "Once per round, your pawn can pass over holes and pawns. Tiles marked ↷ use it automatically. The jump badge under your name shows if you still have it.",
"Points.": "Points.",
"Les cases s'usent.": "Tiles wear out.",
"Le chiffre dit combien de fois on peut encore la quitter. À 0, elle tombe.": "The number tells how many more times you can leave it. At 0, it falls.",
"Tu perds la manche": "You lose the round",
"quand aucun de tes pions ne peut bouger, ou quand ta pendule tombe à 0:00. Chacun a sa pendule : il y a toujours un gagnant.": "when none of your pawns can move, or when your clock hits 0:00. Each player has a clock: there's always a winner.",
"En ligne.": "Online.",
"Chacun doit jouer son premier coup en 15 s, sinon la partie est annulée sans perte de points. Ensuite, quitter l'appli plus de 15 s fait perdre la partie.": "Each player must make their first move within 15 s, or the game is cancelled with no points lost. After that, leaving the app for more than 15 s loses the game.",
"2 manches gagnantes.": "Best of 3 rounds.",
"Chacun commence une manche. À 1-1, le vainqueur avec la plus grande somme restante commence la belle.": "Each player starts one round. At 1-1, the winner with the highest remaining sum starts the decider.",
"Prémove.": "Premove.",
"Pendant le tour adverse, prépare ton coup : il part tout seul s'il est encore possible.": "During your opponent's turn, prepare your move: it plays itself if it's still possible.",
"C'est parti": "Let's go",
"Gagner une manche rapporte 10 points, plus la somme des chiffres encore visibles sur le plateau (les cases sous les pions ne comptent pas). Si cette somme est inférieure à 10, le perdant marque la différence, 5 points au maximum (il reste 5 : 15 à 5 ; il reste 2 : 12 à 5).": "Winning a round earns 10 points, plus the sum of the numbers still visible on the board (tiles under pawns don't count). If that sum is below 10, the loser scores the difference, 5 points max (5 left: 15 to 5; 2 left: 12 to 5).",
"Aucun message. Un petit mot pour ton adversaire ?": "No messages. A word for your opponent?",
"Analyse · manche": "Analysis · round",
"Analyse de": "Analyzing",
"coups en cours…": "moves…",
"L'analyse n'a pas pu se faire.": "The analysis couldn't be done.",
"Aucun coup enregistré sur cet appareil pour cette manche.": "No moves recorded on this device for this round.",
"Meilleur :": "Best:",
"(case verte).": "(green tile).",
"C'était le meilleur coup.": "That was the best move.",
"imprécision": "inaccuracy",
"(case rouge)": "(red tile)",
"Coup": "Move",
"◀ Précédent": "◀ Previous",
"Suivant ▶": "Next ▶",
"Les lettres a à e et les chiffres 1 à 5 donnent la case, comme aux échecs. Cadre pointillé : case de départ. Rouge : coup joué. Vert : meilleur coup. « Victoire manquée » et « Coup perdant » sont certains, le reste est estimé.": "Letters a to e and numbers 1 to 5 give the tile, like in chess. Dotted frame: starting tile. Red: move played. Green: best move. “Missed win” and “Losing move” are certain, the rest is estimated.",
"Partie contre": "Game against",
", l'ordinateur": ", the computer",
"ajouté à tes amis": "added to your friends",
"piques maximum : retire-en une d'abord": "taunts max: remove one first",
"Premium simulé activé": "Simulated Premium on",
"Premium désactivé": "Premium off",
"Acheté et équipé (−": "Bought and equipped (−",
"pièces)": "coins)",
"Achats de démo réinitialisés": "Demo purchases reset",
"Premium débloqué (administrateur)": "Premium unlocked (admin)",
"Ami ajouté. Il apparaîtra en ligne dès qu'il ouvre le jeu.": "Friend added. They'll appear online when they open the game.",
"Cet ami est déjà dans ta liste.": "This friend is already in your list.",
"Temps écoulé pour": "Time's up for",
"série": "streak",
"Relevé aujourd'hui. Reviens demain pour prolonger ta série.": "Done today. Come back tomorrow to extend your streak.",
"Bats": "Beat",
") sur le plateau": ") on the board",
"Défi du jour": "Daily challenge",
"fr-FR": "en-US",
"Installer l'appli": "Install the app",
"Pour installer l'appli sur iPhone : touche Partager dans Safari, puis « Sur l'écran d'accueil ».": "To install the app on iPhone: tap Share in Safari, then “Add to Home Screen”.",
"Isoler en 1 coup": "Isolate in 1 move",
"Bloque l'adversaire en 1 coup.": "Block your opponent in 1 move.",
"Gagner en 2 coups": "Win in 2 moves",
"Gagne en 2 coups.": "Win in 2 moves.",
"Gagner en 3 coups": "Win in 3 moves",
"Gagne en 3 coups.": "Win in 3 moves.",
"Prendre l'avantage": "Take the advantage",
"Trouve le meilleur coup.": "Find the best move.",
"Se déplacer": "Moving",
"1, 2 ou 3 cases en ligne droite.": "1, 2 or 3 tiles in a straight line.",
"Un pion avance en ligne droite : haut, bas, gauche ou droite.": "A pawn moves in a straight line: up, down, left or right.",
"De 1, 2 ou 3 cases d'un coup.": "1, 2 or 3 tiles at a time.",
"Jamais en diagonale, et jamais par-dessus un pion.": "Never diagonally, and never over a pawn.",
"Amène un de tes pions sur la case jaune, en 2 coups maximum.": "Bring one of your pawns to the yellow tile in 2 moves max.",
"Deux déplacements en ligne droite suffisent : d'abord vers le haut, puis sur le côté.": "Two straight moves are enough: first up, then sideways.",
"Les cases s'usent": "Tiles wear out",
"Le chiffre dit combien de fois on peut encore quitter la case.": "The number tells how many more times you can leave the tile.",
"Le chiffre indique combien de fois on peut encore quitter la case.": "The number shows how many more times you can leave the tile.",
"Quand un pion quitte une case 1, elle tombe et laisse un trou.": "When a pawn leaves a 1 tile, it falls and leaves a hole.",
"Une case 2 devient une case 1.": "A 2 tile becomes a 1 tile.",
"Un trou bloque la ligne : on ne peut plus passer par là.": "A hole blocks the line: you can't pass through anymore.",
"Fais tomber 2 cases en 3 coups maximum.": "Make 2 tiles fall in 3 moves max.",
"Quitter une case 1 la fait tomber. Enchaîne deux départs depuis des cases 1.": "Leaving a 1 tile makes it fall. Leave two 1 tiles in a row.",
"Bloquer pour gagner": "Block to win",
"Tu gagnes quand l'adversaire ne peut plus bouger.": "You win when your opponent can't move anymore.",
"Tu perds la manche quand aucun de tes deux pions ne peut bouger.": "You lose the round when neither of your pawns can move.",
"Ici, Blanc peut enfermer les deux pions adverses d'un seul coup.": "Here, White can trap both opposing pawns in a single move.",
"Plus aucun déplacement pour l'adversaire : manche gagnée !": "No moves left for your opponent: round won!",
"Bloque les deux pions adverses en 1 coup.": "Block both opposing pawns in 1 move.",
"Tes pions et les trous ferment chaque ligne de l'adversaire : il ne lui reste aucun déplacement.": "Your pawns and the holes close every line: your opponent has no moves left.",
"Le saut ↷": "The jump ↷",
"Une fois par manche, passe par-dessus un trou ou un pion.": "Once per round, pass over a hole or a pawn.",
"Ce pion est coincé : trous à gauche, à droite et devant.": "This pawn is stuck: holes to the left, right and front.",
"Le saut le fait passer par-dessus le trou. Une seule fois par manche !": "The jump takes it over the hole. Only once per round!",
"Dans le jeu, les cases marquées ↷ utilisent ton saut automatiquement.": "In the game, tiles marked ↷ use your jump automatically.",
"Rejoins la case jaune : il faudra sauter par-dessus la rangée de trous.": "Reach the yellow tile: you'll have to jump over the row of holes.",
"Une rangée de trous coupe le plateau. Seul le saut permet de la traverser.": "A row of holes cuts the board. Only the jump can cross it.",
"Réduire les options, puis enfermer.": "Reduce the options, then trap.",
"Premier coup : couper les sorties de l'adversaire (ici avec le saut).": "First move: cut off your opponent's exits (here with the jump).",
"L'adversaire joue sa meilleure défense…": "Your opponent plays their best defense…",
"…et le second coup l'enferme. Il faut toujours calculer sa réponse.": "…and the second move traps them. Always calculate the reply.",
"Gagne en 2 coups. L'ordinateur défend au mieux.": "Win in 2 moves. The computer defends its best.",
"Ton premier coup réduisait déjà ses déplacements. Le second fermait la dernière issue.": "Your first move already reduced their moves. The second closed the last exit.",
"Contrôler le centre": "Control the center",
"Un pion au centre voit tout le plateau.": "A pawn in the center sees the whole board.",
"La force d'un pion, c'est sa mobilité : le nombre de cases qu'il peut atteindre.": "A pawn's strength is its mobility: the number of tiles it can reach.",
"Au bord, des directions sont perdues. Vers le centre, il en a quatre.": "On the edge, directions are lost. Toward the center, it has four.",
"Plus tu as de déplacements, plus il est dur de t'enfermer.": "The more moves you have, the harder you are to trap.",
"Joue le coup qui te laisse le plus de déplacements possibles.": "Play the move that leaves you the most possible moves.",
"Ce coup rapproche ton pion du centre et des grandes lignes libres : c'est lui qui t'ouvre le plus de cases.": "This move brings your pawn toward the center and the long open lines: it opens the most tiles for you.",
"Couper le plateau": "Cut the board",
"Ferme les lignes de l'adversaire.": "Close your opponent's lines.",
"Un pion posé en travers d'une ligne la coupe : l'adversaire ne peut ni passer, ni s'y poser.": "A pawn placed across a line cuts it: your opponent can't pass or land there.",
"Ici, ton pion bloque la colonne du pion adverse du coin.": "Here, your pawn blocks the column of the opposing pawn in the corner.",
"Il ne lui reste que la ligne du haut. Moins de sorties, c'est plus près de la défaite.": "Only the top row is left. Fewer exits means closer to defeat.",
"Joue le coup qui laisse le moins de déplacements à l'adversaire.": "Play the move that leaves your opponent the fewest moves.",
"Ton pion se place sur ses lignes et les coupe : il perd d'un coup plusieurs sorties.": "Your pawn sits on their lines and cuts them: they lose several exits at once.",
"Garder son saut pour la fin": "Save your jump for the end",
"Le saut gaspillé ne revient pas.": "A wasted jump never comes back.",
"Ton saut est précieux. Gaspillé trop tôt, tu ne pourrais plus gagner ici.": "Your jump is precious. Wasted too early, you couldn't win here.",
"D'abord un coup normal, qui réduit ses options…": "First a normal move that reduces their options…",
"Il se défend comme il peut…": "They defend as best they can…",
"…et le saut, gardé pour la fin, ferme la dernière issue.": "…and the jump, saved for the end, closes the last exit.",
"Gagne en 2 coups. Indice : ne gaspille pas ton saut.": "Win in 2 moves. Hint: don't waste your jump.",
"Le premier coup se joue sans sauter. Le saut sert au coup final, quand il ferme la dernière sortie.": "The first move is played without jumping. The jump is for the final move, when it closes the last exit.",
"Survivre sous pression": "Survive under pressure",
"Trouver la sortie quand tout se referme.": "Find the way out when everything closes in.",
"Parfois, l'adversaire t'étouffe. Avant de bouger, regarde ce qu'il te restera après sa réponse.": "Sometimes your opponent smothers you. Before moving, look at what you'll have left after their reply.",
"Ici, seuls 2 coups sur 6 te gardent en vie pendant trois tours.": "Here, only 2 moves out of 6 keep you alive for three turns.",
"Garde toujours une case de secours pour chacun de tes pions.": "Always keep an escape tile for each of your pawns.",
"Survis 3 tours face à l'ordinateur, qui joue au mieux.": "Survive 3 turns against the computer, which plays its best.",
"Tu as choisi des cases qui gardaient une sortie après chacune de ses réponses.": "You chose tiles that kept an exit after each of its replies.",
"Calculer 3 coups": "Calculate 3 moves",
"Voir la fin avant tout le monde.": "See the end before everyone else.",
"Les meilleurs joueurs calculent trois coups à l'avance. Regarde.": "The best players calculate three moves ahead. Watch.",
"L'adversaire choisit sa meilleure défense…": "Your opponent picks their best defense…",
"On réduit encore ses sorties, ici avec le saut.": "We cut their exits further, here with the jump.",
"Il n'a plus qu'un chemin…": "Only one path left…",
"…et le dernier coup l'enferme.": "…and the last move traps them.",
"Gagne en 3 coups. L'ordinateur défend au mieux.": "Win in 3 moves. The computer defends its best.",
"Ton premier coup lui retirait déjà presque tout. Ensuite, chaque coup fermait une sortie de plus.": "Your first move already took almost everything. Then each move closed one more exit.",
"Compter ses déplacements": "Count your moves",
"Avant de jouer, compte tes cases.": "Before playing, count your tiles.",
"Avant chaque coup, compte les cases que tes deux pions peuvent atteindre.": "Before each move, count the tiles your two pawns can reach.",
"Ce coup en ouvre plus que tous les autres.": "This move opens more than any other.",
"Plus de cases, plus de choix, moins de risques.": "More tiles, more choices, fewer risks.",
"Éviter les coins": "Avoid the corners",
"Le coin est un piège.": "The corner is a trap.",
"Dans un coin, un pion n'a plus que deux directions. Au bord, trois. Au centre, quatre.": "In a corner, a pawn has only two directions. On the edge, three. In the center, four.",
"On sort du bord vers les grandes lignes.": "Leave the edge for the long lines.",
"Reste loin des coins tant que le plateau est plein.": "Stay away from corners while the board is full.",
"Fermer une ligne": "Close a line",
"Ton pion est un mur.": "Your pawn is a wall.",
"Un pion posé sur la ligne de l'adversaire la coupe net.": "A pawn placed on your opponent's line cuts it clean.",
"On se place pile sur sa route.": "Stand right in their way.",
"Chaque ligne fermée lui retire jusqu'à trois cases.": "Each closed line takes up to three tiles from them.",
"Poser un mur": "Build a wall",
"Couper le plateau en deux.": "Cut the board in two.",
"Bien placé, un pion sépare le plateau en deux zones.": "Well placed, a pawn splits the board into two zones.",
"On coupe le passage vers la grande zone.": "Cut off the way to the big zone.",
"Laisse-lui la petite zone, garde la grande.": "Leave them the small zone, keep the big one.",
"Couper et respirer": "Cut and breathe",
"Attaquer sans s'enfermer.": "Attack without trapping yourself.",
"Le meilleur coup réduit ses cases ET garde les tiennes.": "The best move reduces their tiles AND keeps yours.",
"Ce coup gagne sur les deux tableaux.": "This move wins on both fronts.",
"Compte toujours la différence : tes cases moins les siennes.": "Always count the difference: your tiles minus theirs.",
"Le coup qui enferme": "The trapping move",
"Bloquer en un coup.": "Block in one move.",
"Quand l'adversaire n'a plus que quelques sorties, un seul coup peut tout fermer.": "When your opponent has only a few exits left, a single move can close them all.",
"Ce coup ferme la dernière sortie.": "This move closes the last exit.",
"Plus aucun déplacement : manche gagnée.": "No moves left: round won.",
"Le piège à deux pions": "The two-pawn trap",
"Bloquer ses deux pions d'un coup.": "Block both pawns in one move.",
"Ses deux pions partagent parfois la même sortie.": "Their two pawns sometimes share the same exit.",
"Une seule case les bloque tous les deux.": "A single tile blocks them both.",
"Deux pions, un seul coup : efficace.": "Two pawns, one move: efficient.",
"Garder une sortie": "Keep an exit",
"Ne jamais finir sans issue.": "Never end up with no way out.",
"Avant de bouger, demande-toi : après sa réponse, pourrai-je encore jouer ?": "Before moving, ask yourself: after their reply, will I still be able to move?",
"Ce coup garde une sortie quoi qu'il fasse.": "This move keeps an exit whatever they do.",
"Il a répondu, et tu peux encore bouger.": "They replied, and you can still move.",
"Fuir vers l'espace": "Run to open space",
"Courir vers la grande zone.": "Head for the big zone.",
"Quand ça se referme, file vers l'endroit où il reste le plus de cases.": "When it closes in, run where the most tiles are left.",
"Premier pas vers l'espace…": "First step toward open space…",
"Deux tours plus tard, tu respires encore.": "Two turns later, you're still breathing.",
"Le saut de secours": "The rescue jump",
"S'évader en sautant.": "Escape by jumping.",
"Parfois, le seul moyen de survivre est de passer par-dessus.": "Sometimes the only way to survive is to go over.",
"Le saut te sort de la zone qui se referme.": "The jump gets you out of the closing zone.",
"Sans le saut, c'était perdu.": "Without the jump, it was lost.",
"Sauter pour attaquer": "Jump to attack",
"Le saut comme arme.": "The jump as a weapon.",
"Le saut peut aussi servir à attaquer : il atteint des cases inaccessibles autrement.": "The jump can also attack: it reaches tiles you couldn't otherwise.",
"Un saut, et la porte se ferme.": "One jump, and the door shuts.",
"Un saut bien placé vaut une victoire.": "A well-placed jump is worth a win.",
"Deux coups d'avance": "Two moves ahead",
"Calculer sa réponse.": "Calculate their reply.",
"Gagner en deux coups, c'est prévoir la réponse de l'adversaire.": "Winning in two moves means predicting your opponent's reply.",
"Premier coup : il réduit ses options.": "First move: it reduces their options.",
"Le second coup ferme tout.": "The second move closes everything.",
"L'étau": "The vise",
"Serrer des deux côtés.": "Squeeze from both sides.",
"Tes deux pions peuvent travailler ensemble comme un étau.": "Your two pawns can work together like a vise.",
"Un pion serre d'un côté…": "One pawn squeezes from one side…",
"…l'autre ferme de l'autre côté.": "…the other closes the other side.",
"Défense de maître": "Master defense",
"Survivre trois tours, encore.": "Survive three turns, again.",
"Ici, presque tous les coups perdent. Trouve celui qui tient.": "Here, almost every move loses. Find the one that holds.",
"Le bon coup garde une sortie à chaque tour.": "The right move keeps an exit every turn.",
"Une défense de champion.": "A champion's defense.",
"L'examen final": "The final exam",
"Prouve que tu es très fort.": "Prove you're really strong.",
"Dernier cours : une victoire en trois coups contre la meilleure défense.": "Last lesson: a win in three moves against the best defense.",
"Le chemin commence ici.": "The path starts here.",
"Bravo : tu fais partie des très forts.": "Bravo: you're one of the very best.",
"Trouve le coup qui donne le plus grand écart : tes déplacements moins les siens.": "Find the move with the biggest gap: your moves minus theirs.",
"Gagne en 1 coup.": "Win in 1 move.",
"Survis 1 tour : après la réponse de l'ordinateur, tu dois encore pouvoir bouger.": "Survive 1 turn: after the computer's reply, you must still be able to move.",
"Survis 2 tours face à l'ordinateur.": "Survive 2 turns against the computer.",
"Survis 3 tours face à l'ordinateur.": "Survive 3 turns against the computer.",
"Survis 2 tours. Tout se referme…": "Survive 2 turns. Everything is closing in…",
"Ce coup ouvre de nouvelles lignes à tes pions : c'est lui qui te donne le plus de cases.": "This move opens new lines for your pawns: it gives you the most tiles.",
"Ton pion se pose sur ses lignes et lui retire le plus de sorties.": "Your pawn lands on their lines and takes away the most exits.",
"Ce coup fait les deux à la fois : il t'ouvre des cases et en ferme chez lui.": "This move does both: it opens tiles for you and closes theirs.",
"Chaque coup lui retirait des sorties, jusqu'à la dernière.": "Each move took away exits, down to the last one.",
"Tu as choisi des cases qui gardaient toujours une sortie après sa réponse.": "You chose tiles that always kept an exit after their reply.",
"Seul le saut permettait de quitter la zone qui se refermait.": "Only the jump could leave the closing zone.",
"Le saut atteint la seule case qui ferme sa dernière sortie.": "The jump reaches the only tile that closes their last exit.",
"L'adversaire se défend au mieux…": "Your opponent defends their best…",
"On continue…": "Keep going…",
"Les bases": "The basics",
"Stratégie": "Strategy",
"Mobilité et murs": "Mobility and walls",
"Attaque et défense": "Attack and defense",
"Saut et calcul": "Jump and calculation",
"+5 pièces": "+5 coins",
"BRAVO": "BRAVO",
"Objectif pas atteint dans le nombre de coups. Réessaie !": "Goal not reached in the number of moves. Try again!",
"Après ton coup, tu as": "After your move, you have",
"déplacements possibles et l'adversaire": "possible moves and your opponent",
"C'est l'avantage : plus de liberté pour toi, moins pour lui.": "That's the advantage: more freedom for you, less for them.",
"Ce n'était pas le meilleur coup. Cherche celui qui te laisse plus de déplacements et lui en laisse moins. (La solution est réservée à Premium.)": "That wasn't the best move. Look for the one that leaves you more moves and them fewer. (The solution is for Premium.)",
"Le meilleur coup était": "The best move was",
": il te laissait": ": it left you",
"déplacements et seulement": "moves and only",
"à l'adversaire.": "for your opponent.",
"Ton premier coup": "Your first move",
"lui avait déjà retiré presque toutes ses sorties.": "had already taken almost all their exits.",
"Après ton dernier coup, l'adversaire n'a plus aucun déplacement : ses pions sont enfermés par les trous, les bords et tes pions.": "After your last move, your opponent has no moves left: their pawns are trapped by holes, edges and your pawns.",
"L'adversaire peut encore bouger. La solution commençait par": "Your opponent can still move. The solution started with",
"L'adversaire peut encore bouger. Regarde quelles lignes il lui reste, et réessaie.": "Your opponent can still move. Look at which lines they have left, and try again.",
"L'adversaire t'a bloqué. Réessaie !": "Your opponent blocked you. Try again!",
"Lastep du jour ·": "Daily Lastep ·",
"Défi de": "Challenge from",
"/3 erreurs": "/3 mistakes",
"Cours": "Lesson",
"Démonstration terminée. À toi de jouer !": "Demo over. Your turn!",
"Réussi !": "Solved!",
"Raté.": "Missed.",
"Raté. Réessaie ou regarde la solution.": "Missed. Try again or see the solution.",
"Analyse de ton coup…": "Analyzing your move…",
"L'adversaire réfléchit…": "Your opponent is thinking…",
"Précédent": "Previous",
"À l'exercice": "To the exercise",
"Suivant": "Next",
"Revoir la fin": "Replay the end",
"Revoir tout": "Replay all",
"À toi !": "Your turn!",
"Arrêter le défi": "Stop the challenge",
"Solution": "Solution",
"Recommencer": "Restart",
"Une démonstration animée, puis un exercice à réussir. Commence par le cours 1.": "An animated demo, then an exercise to solve. Start with lesson 1.",
"Chapitre": "Chapter",
", terminé": ", done",
", Premium": ", Premium",
"Tous les cours": "All lessons",
"🏅 Badges": "🏅 Badges",
"Fermer le menu": "Close menu",
"Saison 1 · bientôt": "Season 1 · soon",
"Leçon suivante": "Next lesson",
"Premium ✓": "Premium ✓",
"Bientôt : il faut d'abord des parties de vrais champions": "Soon: we first need games from real champions",
"réussis": "solved",
"Des positions réelles, vérifiées par calcul : la solution existe toujours.": "Real positions, verified by computer: there's always a solution.",
"Pas encore…": "Not yet…",
"Défier un ami sur ce puzzle": "Challenge a friend on this puzzle",
"Voir la solution": "See the solution",
"Solution · Premium": "Solution · Premium",
"Retour au parcours": "Back to the path",
"Retour à la liste": "Back to the list",
"Victoire par abandon !": "Win by resignation!",
"Partie abandonnée": "Game resigned",
"gagne !": "wins!",
"Tu gagnes !": "You win!",
"en ami": "as friend",
"🎬 Clip du coup gagnant": "🎬 Winning move clip",
"Points :": "Points:",
"Premier Pas": "First Step",
"Termine le cours 1.": "Finish lesson 1.",
"Premier de la classe": "Top of the class",
"Termine les 5 cours.": "Finish the 5 lessons.",
"L'Isoleur": "The Isolator",
"Réussis 3 puzzles « Isoler en 1 coup ».": "Solve 3 “Isolate in 1 move” puzzles.",
"Terminator": "Terminator",
"Réussis tous les puzzles « Gagner en 3 coups ».": "Solve all “Win in 3 moves” puzzles.",
"Grand Stratège": "Grand Strategist",
"Réussis 3 puzzles « Prendre l'avantage ».": "Solve 3 “Take the advantage” puzzles.",
"Sniper": "Sniper",
"Réussis 5 puzzles du premier coup.": "Solve 5 puzzles on the first try.",
"Blitz": "Blitz",
"Gagne une manche en 10 coups ou moins.": "Win a round in 10 moves or fewer.",
"Attaque": "Attack",
"Kangourou": "Kangaroo",
"Gagne une manche avec ton saut au dernier coup.": "Win a round with your jump on the last move.",
"Mur de briques": "Brick wall",
"Gagne une manche alors qu'un de tes pions était coincé.": "Win a round while one of your pawns was stuck.",
"Défense": "Defense",
"Sang-froid": "Cool head",
"Gagne une manche avec moins de 10 s à ta pendule.": "Win a round with less than 10 s on your clock.",
"Démolisseur": "Wrecker",
"Fais tomber 50 cases.": "Make 50 tiles fall.",
"Fun": "Fun",
"Roi de la belle": "Decider king",
"Gagne une partie à la belle.": "Win a game in the decider.",
"Carton plein": "Clean sweep",
"Gagne une partie 2-0.": "Win a game 2-0.",
"Tombeur de Sphinx": "Sphinx slayer",
"Bats Le Sphinx.": "Beat The Sphinx.",
"Chambreur": "Teaser",
"Envoie 10 wizz, toc toc ou haha.": "Send 10 buzz, knock or haha.",
"Moine zen": "Zen monk",
"Gagne une partie sans aucune taquinerie.": "Win a game without any teasing.",
"Insomniaque": "Night owl",
"Joue une partie entre minuit et 5 h.": "Play a game between midnight and 5 am.",
"Marathonien": "Marathoner",
"Termine 20 parties.": "Finish 20 games.",
"En feu": "On fire",
"Joue le Lastep du jour 3 jours de suite.": "Play the Daily Lastep 3 days in a row.",
"Pote de tous": "Everyone's buddy",
"Ajoute 3 amis.": "Add 3 friends.",
"Social": "Social",
"Gladiateur": "Gladiator",
"Gagne une partie en ligne.": "Win an online game.",
"Nouveau badge · +20 pièces": "New badge · +20 coins",
"Obtenu.": "Earned.",
"À débloquer.": "Locked.",
"Pas encore vu en ligne": "Not seen online yet",
"Vu à l'instant": "Seen just now",
"Vu il y a": "Seen",
"Vu le": "Seen on",
"Joueur": "Player",
"t'a ajouté en ami": "added you as a friend",
"est déjà en partie.": "is already in a game.",
"a refusé le défi.": "declined the challenge.",
"Ajoute-moi sur Lastep ! Mon code ami :": "Add me on Lastep! My friend code:",
"Rejoins-moi sur Lastep ! Ajoute-moi en ami :": "Join me on Lastep! Add me as a friend:",
"Personne n'est disponible à cette cadence pour le moment. Réessaie dans un instant, change de cadence, ou invite un ami.": "Nobody is available at this time control right now. Try again in a moment, change time control, or invite a friend.",
"En attente d'un joueur (file": "Waiting for a player (queue",
"Un joueur attend : connexion… (file": "A player is waiting: connecting… (queue",
"LE JEU DE STRATÉGIE OÙ LES CASES S'USENT": "THE STRATEGY GAME WHERE TILES WEAR OUT",
"ORDINATEUR": "COMPUTER",
"Classement national : bientôt": "National ranking: soon",
"Bientôt sur l'App Store et Google Play": "Coming soon to the App Store and Google Play",
"Viens me défier sur Lastep ! Mon code ami :": "Come challenge me on Lastep! My friend code:",
"Poster enregistré": "Poster saved",
"Temps écoulé !": "Time's up!",
"validé": "cleared",
"débloqué !": "unlocked!",
"Tous les paliers validés !": "All tiers cleared!",
"Étape": "Step",
", réussi": ", solved",
", verrouillé": ", locked",
"Puzzle": "Puzzle",
"Progression": "Progress",
"Calme": "Calm",
"Thème calme, moins lumineux": "Calm theme, less bright",
"Pas encore d'amis ici. Partage ton lien ou ton code ami": "No friends here yet. Share your link or friend code",
": vous pourrez vous défier et comparer vos progrès.": ": you'll be able to challenge each other and compare progress.",
"Tes amis": "Your friends",
"min · 5×5": "min · 5×5",
"Ordinateur": "Computer",
"min ·": "min ·",
"Thème calme": "Calm theme",
"Moins lumineux, plus reposant pour les yeux.": "Less bright, easier on the eyes.",
"· Premium": "· Premium",
"Tu ne les reçois plus, mais tu ne peux plus en envoyer.": "You won't receive them, but you can't send any either.",
"Réservé à Premium. Sinon, coupe les sons : les animations restent.": "Premium only. Otherwise, turn off sounds: the animations stay.",
"Musique pendant les parties": "Music during games",
"Afficher les messages de l'adversaire": "Show opponent's messages",
"Lastep · version": "Lastep · version",
"Éclair · 1 min": "Blitz · 1 min",
"🧩 Lastep du jour": "🧩 Daily Lastep",
"3 puzzles · un seul essai chacun · le même pour tout le monde": "3 puzzles · one try each · the same for everyone",
"jours ·": "days ·",
"🧩 Lastep #": "🧩 Lastep #",
"Nouveau puzzle demain": "New puzzle tomorrow",
"J'ai résolu ce puzzle Lastep en": "I solved this Lastep puzzle in",
"s. Fais mieux !": "s. Beat that!",
"a rejoint grâce à toi : +100 pièces": "joined thanks to you: +100 coins",
"Trouveras-tu": "Can you find",
"le coup gagnant ?": "the winning move?",
"Le coup gagnant": "The winning move",
"Lastep · défie-moi": "Lastep · challenge me",
"Bloqué. Partie gagnée.": "Blocked. Game won.",
"Trouveras-tu le coup gagnant ?": "Can you find the winning move?",
"Vidéo enregistrée": "Video saved",
"💥 Tu as marché sur la bombe !": "💥 You stepped on the bomb!",
"a marché sur ta bombe !": "stepped on your bomb!",
"désamorce sa propre bombe": "defuses their own bomb",
"3 coups chacun : les bombes sont désamorcées": "3 moves each: the bombs are defused",
"BOUM": "BOOM",
"Partie annulée": "Game cancelled",
"Personne ne perd de points.": "Nobody loses points.",
"Tu n'as pas joué ton premier coup à temps.": "You didn't play your first move in time.",
"Ton adversaire a quitté la partie : victoire !": "Your opponent left the game: you win!",
"Connexion perdue avant le premier coup.": "Connection lost before the first move.",
"Ton adversaire ne répond plus…": "Your opponent isn't responding…",
"Partie perdue": "Game lost",
"Tu as quitté l'appli plus de 15 secondes pendant la partie.": "You left the app for more than 15 seconds during the game.",
"Tu as quitté l'appli avant le premier coup.": "You left the app before the first move.",
"✅ Réussi !": "✅ Solved!",
"❌ Raté": "❌ Missed",
"Attends…": "Wait…",
"Exercice": "Exercise",
"Série": "Streak",
"de suite !": "in a row!",
"Ton ami": "Your friend",
"Bienvenue : +100 pièces grâce à ton ami": "Welcome: +100 coins thanks to your friend",
"contre": "vs",
"commence": "starts",
"En attente de sa réponse…": "Waiting for their reply…",
"Tu en as": "You have",
"essai": "try",
"essais": "tries",
"Tu as maîtrisé": "You've mastered",
"pour les réseaux sociaux": "for social media",
"piques": "taunts",
"gagne": "wins",
"grave": "blunder",
"graves": "blunders",
"imprécisions": "inaccuracies",
"joue": "plays",
"coup restant": "move left",
"coups restants": "moves left",
"sur": "of",
"amis": "friends",
"m.": "g.",
"victoire": "win",
"annulation": "cancellation",
"dans": "in",
"jour": "day",
"jours": "days",
"manche(s) gagnée(s)": "round(s) won",
"trou": "hole",
"case": "tile",
"Explication précédente": "Previous explanation",
"Explication suivante": "Next explanation",
"pièces. Ouvrir la boutique": "coins. Open the shop",
"Réglages : sons, musique, thème, règles": "Settings: sounds, music, theme, rules",
"Langue": "Language",
"Fin de partie": "Game over"
};
// Partie à 4
Object.assign(window.EN_DICT,{
"Partie à 4": "4-player game",
"NOUVEAU": "NEW",
"est éliminé (absent).": "is out (away).",
"est bloqué : éliminé !": "is blocked: out!",
"fait le dernier pas !": "takes the last step!",
"a quitté : l'ordinateur le remplace.": "left: the computer takes over.",
"L'hôte a quitté la partie.": "The host left the game.",
"Cette salle est complète ou la partie a déjà commencé.": "This room is full or the game has already started.",
"Éliminé": "Out",
"Jusqu'à 4 joueurs sur un plateau 6×6, un pion et deux sauts chacun. Bloqué à ton tour : éliminé. Le dernier debout gagne.": "Up to 4 players on a 6×6 board, one pawn and two jumps each. Blocked on your turn: you're out. Last one standing wins.",
"Partie rapide en ligne": "Quick online game",
"Avec d'autres joueurs. S'il en manque, des ordinateurs complètent la table.": "With other players. If some are missing, computers fill the table.",
"Créer une salle pour mes amis": "Create a room for my friends",
"Envoie le lien, lance quand tout le monde est là.": "Send the link, start when everyone's in.",
"Rejoindre une salle": "Join a room",
"Sur ce téléphone": "On this phone",
"Humain": "Human",
"Vide": "Empty",
"Lancer la partie": "Start the game",
"En attente…": "Waiting…",
"Partie rapide": "Quick game",
"Salle privée": "Private room",
"Code de la salle": "Room code",
"Recherche de joueurs…": "Looking for players…",
"ensuite, des ordinateurs complètent la table.": "then computers fill the table.",
"Les places vides seront jouées par l'ordinateur.": "Empty seats will be played by the computer.",
"L'hôte lance la partie quand tout le monde est là.": "The host starts the game when everyone's in.",
"Il faut au moins 2 joueurs.": "You need at least 2 players.",
"Viens jouer à 4 sur Lastep ! Code de la salle :": "Come play 4-player Lastep! Room code:"
});
Object.assign(window.EN_DICT,{"choisis un pion": "pick a pawn", "touche une case marquée": "tap a marked tile"});
Object.assign(window.EN_DICT,{"Tape le code que ton ami t'a donné.": "Type the code your friend gave you.", "Créer une salle": "Create a room", "Tu donnes le code à tes amis, ils le tapent, tu lances.": "Give the code to your friends, they type it, you start.", "Dis ce code à tes amis : ils le tapent dans Partie à 4.": "Tell your friends this code: they type it in 4-player game.", "Copier le code": "Copy the code", "Partager le lien": "Share the link", "Code copié": "Code copied"});
Object.assign(window.EN_DICT,{"Crée une partie et dis le code à ton ami, ou tape le code qu'il t'a donné. Cadence :": "Create a game and tell your friend the code, or type the code they gave you. Time control:", "Le code fait 4 chiffres.": "The code has 4 digits.", "Dis ce code à ton ami et garde cet écran ouvert. S'il est loin, copie le code ou partage le lien.": "Tell your friend this code and keep this screen open. If they're far away, copy the code or share the link."});
Object.assign(window.EN_DICT,{"Choisis la cadence, crée la partie et dis le code à ton ami. Ou tape le code qu'il t'a donné : c'est sa cadence qui compte.": "Pick the time control, create the game and tell your friend the code. Or type the code they gave you: their time control applies."});
Object.assign(window.EN_DICT,{"Jouer une partie à 4": "Play a 4-player game", "Tu fais le dernier pas !": "You take the last step!"});
Object.assign(window.EN_DICT,{"Temps par joueur et par manche. Quelle que soit la cadence, chacun commence une manche : il faut 2 manches gagnées.": "Time per player per round. Whatever the time control, each player starts one round: you need 2 round wins.", "Revanche": "Rematch"});
Object.assign(window.EN_DICT,{"Doux": "Soft", "Brillant": "Glossy", "Chrome": "Chrome", "Cristal": "Crystal", "Holo": "Holo", "Finition": "Finish", "Finitions": "Finishes", "Rare": "Rare", "Épique": "Epic", "Légendaire": "Legendary"});
Object.assign(window.EN_DICT,{"Sympa": "Friendly", "Changer mes piques": "Change my taunts", "Aucune": "None", "Étincelles": "Sparkles", "Flammes": "Flames", "Arc-en-ciel": "Rainbow", "Galaxie": "Galaxy", "Confettis": "Confetti", "Feu d'artifice": "Fireworks", "Pluie d'étoiles": "Star shower", "Pluie d'or": "Gold rain", "Couronne royale": "Royal crown", "Traînée": "Trail", "Célébration": "Celebration", "Traînées": "Trails", "Célébrations de victoire": "Victory celebrations"});
Object.assign(window.EN_DICT,{"Avec un ami": "With a friend", "À 4 joueurs": "4 players", "Contre l'ordinateur": "Vs computer", "Avec l'entraîneur": "With the coach", "1 bombe cachée chacun": "1 hidden bomb each", "Bloquer les taquineries": "Block teasing"});
Object.assign(window.EN_DICT,{"Tout débloquer (test)": "Unlock everything (test)", "Tout reverrouiller": "Lock everything again", "Toute la boutique est débloquée": "The whole shop is unlocked", "Boutique reverrouillée": "Shop locked again"});
Object.assign(window.EN_DICT, {
  "Premiers pas":"First steps","Cases doubles":"Double tiles","Le saut":"The jump","Maître du parcours":"Path master",
  "Parcours":"Path","🧭 Parcours":"🧭 Path","Chapitre":"Chapter","étoiles":"stars","Étoiles":"Stars","Reste":"Left",
  "Fais tomber toutes les cases.":"Make every tile fall.","Bloqué : il reste des cases.":"Stuck: tiles are left.",
  "4 défis · 1 essai":"4 challenges · 1 try",
  "3 puzzles et 1 parcours · un seul essai chacun · le même pour tout le monde":"3 puzzles and 1 path · one try each · the same for everyone"
});
Object.assign(window.EN_DICT, {
  "Zéro publicité":"Zero ads","Aventure":"Adventure","Arène":"Arena","Déjà récupéré. Reviens demain !":"Already claimed. Come back tomorrow!",
  "Coffre déjà ouvert. Nouvelle barre dans":"Chest already opened. New bar in","Joue encore":"Play","pour ouvrir le coffre":"more to open the chest",
  "Équipé !":"Equipped!","Parfait !":"Perfect!","Génial !":"Awesome!","Bloqué !":"Stuck!","Niveau":"Level","×2 pièces":"×2 coins","+20 secondes":"+20 seconds",
  "Publicité":"Ad","Emplacement de test : la vraie publicité arrivera avec l'appli des stores.":"Test slot: real ads will come with the store app.",
  "Récupérer la récompense":"Claim reward","Passer dans":"Skip in","Passer":"Skip","Fermer sans récompense":"Close without reward",
  "Coffre en bois":"Wooden chest","Coffre d'argent":"Silver chest","Coffre d'or":"Gold chest","Ouvrir le coffre":"Open the chest","Touche pour ouvrir":"Tap to open",
  "Gagné !":"You won!","Équiper":"Equip","Super !":"Great!","Cadeau du jour":"Daily gift","🧰 Coffre de jeu prêt ! Ouvre-le à l'accueil.":"🧰 Play chest ready! Open it on the home screen.",
  "30 minutes de jeu":"30 minutes of play","Roue de la chance":"Lucky wheel","Tourner":"Spin","gratuit":"free","Tourner encore":"Spin again",
  "Reviens demain pour un nouveau tour gratuit.":"Come back tomorrow for a free spin.","Fin de la ligue dans":"League ends in","Top 10":"Top 10",
  "Classement par steps, sur les 30 derniers jours.":"Ranked by steps over the last 30 days.","Classement":"Leaderboard","Chargement…":"Loading…","toi":"you",
  "Hors ligne : seuls toi et les personnages du jeu sont affichés.":"Offline: only you and the game characters are shown.",
  "XP : 10 par étoile, 5 par puzzle réussi, 5 par victoire contre l'ordi.":"XP: 10 per star, 5 per solved puzzle, 5 per win against the computer.",
  "Ligue de la semaine":"Weekly league","Jour":"Day","jour":"day","Coffre de jeu":"Play chest","Ouvrir !":"Open!","Ligue":"League","Seul contre le jeu":"Solo against the game",
  "Contre de vrais joueurs":"Against real players","steps":"steps","Combattre":"Fight","Du jour":"Daily","Chrono":"Timed","Temps écoulé !":"Time's up!","Gratuit":"Free","Joueur":"Player"
});
Object.assign(window.EN_DICT, {
  "Tu gagnes la manche":"You win round","remporte la manche":"wins round","Fin de la manche":"End of round",
  "Points de la manche":"Round points","Voir le plateau":"See the board"
});
Object.assign(window.EN_DICT, {"Taquiner":"Tease","Plus de taquineries":"No teases left","Plus de taquineries pour cette partie.":"No teases left this game.","Attends":"Wait","Wizz":"Wizz","Toc toc":"Knock knock","Haha":"Haha"});
Object.assign(window.EN_DICT, {"Rejoindre le vocal":"Join voice chat","Micro coupé":"Mic off","Micro ouvert":"Mic on","Quitter le vocal":"Leave voice chat",
"Vocal activé : tes amis t'entendent":"Voice on: your friends can hear you","Micro refusé : autorise le micro dans les réglages du téléphone.":"Microphone blocked: allow it in your phone settings.",
"Vocal indisponible sur cet appareil.":"Voice chat isn't available on this device.","Réécouter":"Unmute","Couper sa voix":"Mute them",
"Facultatif : parlez-vous pendant la partie, même chacun chez soi. Rien n'est enregistré.":"Optional: talk during the game, even from home. Nothing is recorded."});
Object.assign(window.EN_DICT, {"Vibrations":"Vibrations"});
Object.assign(window.EN_DICT, {"Forme":"Shape","Finition":"Finish","Accessoire":"Accessory","Traînée":"Trail","Célébration":"Celebration","Plateau":"Board","à débloquer":"to unlock","tout possédé":"all owned","possédé(s)":"owned","Vestiaire":"Wardrobe","Boutique":"Shop","Tu as déjà tout dans cette catégorie !":"You already own everything here!","Rien ici pour l'instant":"Nothing here yet","touche pour voir":"tap to preview","Acheter":"Buy","Équiper":"Equip","Il te manque":"You need","pièces":"coins","acheté et équipé !":"bought and equipped!","Acheter des pièces":"Buy coins","Tu as":"You have","Populaire":"Popular","Meilleur prix":"Best value","Les pièces servent uniquement à débloquer des apparences. Elles ne donnent aucun avantage en partie.":"Coins only unlock looks. They give no advantage in games.","Paiement bientôt disponible avec l'appli des stores.":"Payments coming soon with the store app.","Ordinateur":"Computer","Entraîneur":"Coach","parties":"games","puzzles":"puzzles","badges":"badges","jours de suite":"days in a row","Précédent":"Previous","Suivant":"Next"});
Object.assign(window.EN_DICT, {"ton niveau":"your level","Recherche la plus large atteinte":"Widest search reached","La recherche s'élargit peu à peu":"The search widens little by little","Un joueur de ton niveau attend : connexion…":"A player at your level is waiting: connecting…","Personne de ton niveau ne cherche à cette cadence pour l'instant.":"No one at your level is searching at this time control right now."});
Object.assign(window.EN_DICT, {"Recherche d'un adversaire":"Looking for an opponent","Personne de ton niveau pour l'instant":"No one at your level right now","te défie. Tu acceptes ?":"challenges you. Accept?","Non":"No","Oui, au combat !":"Yes, let's fight!","Chercher encore":"Search again","Adversaire trouvé !":"Opponent found!"});
Object.assign(window.EN_DICT, {"Personne n'ose venir… Moi, je ne fuis jamais le combat.":"Nobody dares to show up… Me, I never run from a fight.","Et toi ?":"Do you?","Oui !":"Yes!","Chercher encore un joueur":"Look for a player again","Jamais ! Au combat !":"Never! Let's fight!","Une autre fois…":"Another time…"});
Object.assign(window.EN_DICT, {"Fuir":"Run away","Accepter":"Accept"});
Object.assign(window.EN_DICT, {"Fin dans":"Ends in","Steps des 30 derniers jours. Les personnages 🤖 servent de repères.":"Steps over the last 30 days. Game characters 🤖 are there as benchmarks."});
Object.assign(window.EN_DICT, {"Steps des 30 derniers jours.":"Steps over the last 30 days.","personnage du jeu, à dépasser":"game character to beat"});
Object.assign(window.EN_DICT, {"Catégories":"Categories"});
// v70 : Chrono, mode assisté
Object.assign(window.EN_DICT, {
"Temps écoulé !":"Time's up!","Série de 3 : +5 s !":"3 in a row: +5 s!","Nouveau record !":"New record!","points":"points",
"casse-têtes réussis":"puzzles solved","casse-tête réussi":"puzzle solved","record":"best","Prochain coffre à":"Next chest at","Rejouer":"Play again","Retour":"Back",
"Gagne en":"Win in","coups":"moves","coup":"move","Bloque l'adversaire. Il défend au mieux.":"Block your opponent. They defend as well as they can.",
"Excellent !":"Excellent!","Bon coup":"Good move","Imprécis":"Inaccurate","Erreur":"Mistake","Gaffe !":"Blunder!","Bien résisté":"Well held",
"Assisté":"Assisted","Assistant":"Assistant","Mode assisté : partie hors classement":"Assisted mode: unranked game",
"Bravo ! Si tu joues bien, tu peux gagner en":"Well done! Play it right and you can win in","À toi de trouver comment.":"Find out how.",
"Tu as une victoire forcée. Cherche-la !":"You have a forced win. Find it!",
"Position difficile : l'adversaire peut te bloquer en":"Tough spot: your opponent can block you in",
"Tiens le plus longtemps possible, ou annule ton dernier coup.":"Hold on as long as you can, or undo your last move.",
"Attention ici : un mauvais coup et tu perds en":"Careful here: one wrong move and you lose in",
"Attention : certains coups ici sont des pièges.":"Careful: some moves here are traps.",
"Tu as l'avantage. Garde plus de sorties que lui.":"You're ahead. Keep more ways out than them.",
"Il a plus de liberté que toi. Cherche à lui couper des sorties.":"They have more room than you. Try to cut off their ways out.",
"Position équilibrée. Réfléchis bien.":"Balanced position. Think it through.",
"L'assistant analyse ton coup…":"The assistant is checking your move…",
"Tu avais une victoire forcée. Annule et cherche-la !":"You had a forced win. Undo and find it!",
"Aïe : l'adversaire peut maintenant te bloquer en":"Ouch: your opponent can now block you in","Annule pour corriger.":"Undo to fix it.",
"Le meilleur coup possible.":"The best possible move.","Bon choix, proche du meilleur.":"Good choice, close to the best.",
"Il y avait mieux. Tu peux annuler et réessayer.":"There was better. You can undo and try again.",
"Ce coup lui donne l'avantage. Annule et cherche mieux.":"This move gives them the edge. Undo and look for better.",
"Jauge de l'assistant":"Assistant gauge","Joue ton coup : l'assistant te dira s'il est bon.":"Make your move: the assistant will tell you if it's good.",
"Mode assisté · Premium":"Assisted mode · Premium",
"Une jauge te dit si chaque coup est bon ou mauvais, et l'assistant te prévient quand tu peux gagner ou perdre dans quelques coups. Il ne te donne jamais le coup : c'est à toi de le trouver. Tu peux annuler tes coups pour réussir une partie parfaite.":"A gauge tells you whether each move is good or bad, and the assistant warns you when you can win or lose within a few moves. It never gives you the move: finding it is up to you. You can undo moves to play a perfect game.",
"Passer en mode assisté ?":"Switch to assisted mode?",
"La partie est déjà commencée et compte pour ton classement. En mode assisté, elle ne comptera plus : elle est comptée comme abandonnée pour le classement.":"This game has already started and counts for your ranking. In assisted mode it no longer counts: it is scored as a resignation for your ranking.",
"Activer l'assistant":"Turn on the assistant","· assisté":"· assisted","D'accord":"OK"
});
